POST localhost:8081/api/service-order
Content-Type: application/json

{
  "customerId": 1,
  "companyId": 1,
  "staffId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 2,
      "discount": 0
    },
    {
      "productId": 1,
      "quantity": 1,
      "discount": 5
    },
    {
      "productId": 1,
      "quantity": 3,
      "discount": 10
    }
  ]
}